<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="lidar_length" value="0.1" />
    <xacro:property name="lidar_width" value="0.01" />
    <xacro:property name="lidar_height" value="0.05" />

    <link name="lidar_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}" />
            </geometry>
            <material name="red" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.2" l="${lidar_length}" w="${lidar_width}" h="${lidar_height}"
            xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </link>


    <joint name="base_lidar_joint" type="fixed">
        <origin xyz="0.0 0.0 ${base_height + lidar_height/2}" rpy="0.0 0.0 0.0" />
        <parent link="base_link" />
        <child link="lidar_link" />
    </joint>


    <!-- hokuyo -->
    <gazebo reference="lidar_link">
        <material>Gazebo/Green</material>
        <sensor type="ray" name="head_hokuyo_sensor">
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.570796</min_angle>
                        <max_angle>1.570796</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.50</min>
                    <max>5.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.004</stddev>
                </noise>
            </ray>

            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">

                <!-- <output_type>sensor_msgs/PointCloud2</output_type> -->
                <min_intensity>100.0</min_intensity>

                <output_type>sensor_msgs/LaserScan</output_type>
                <frameName>lidar_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>